### PR TITLE
Test using php 8

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by prewk** [comment]
Thanks for keeping things up to date, it seems some other magic sauce is needed for travis to use PHP 8 though

**Comment by snapshotpl** [comment]
@prewk what are you think to drop php < 7.2? Currently will be hard to maintain code from 5.3 to 8.0.

**Comment by prewk** [comment]
Sure! We can bump a major version for it.

Can you do a PR for it? And update the readme with a note about which versions supports what?

👍

**Comment by prewk** [comment]
Dumb question: Why does phpunit not run the tests when I run `./vendor/bin/phpunit` or `composer test`?

I have to explicitly run `composer test tests` (`tests` is the directory)

**Pull request merged**
